### ISSUE TITLE
admin_html_head.php  BUG

### ISSUE THREAD

**Issue by ptzjl** [Zen4All-nl/Zen-Cart-Collect-Info-Through-Tabs-In-New-Style#14]
prompt
zen4all_categories.php on line 25

<?php  require('includes/admin_html_head.php');  ?>

required 'includes / admin_html_head.php'
error

The file admin_html_head.php does not exist

php7.2 zen-cart 1.5.6

**Comment by Zen4All** [comment]
Thanks, I'll fix it in the next beta
Currently the focus lies on the categorie product listing

**Comment by Zen4All** [comment]
@ptzjl the header is fixed, along with some other things like renaming the css, and JavaScript files
