### ISSUE TITLE
page BUG

### ISSUE THREAD

**Issue by ptzjl** [Zen4All-nl/Zen-Cart-Collect-Info-Through-Tabs-In-New-Style#15]
Thank you for your timely modification, great plugin, but it still error, please refer to:：

1.Bottom of page :

// attribute copier to product case 'attribute_features_copy_to_category': $_GET['categories_update_id'] = ''; $heading[] = array('text' => '
' . TEXT_INFO_HEADING_ATTRIBUTE_FEATURES . $pInfo->products_id . '
'); $contents = array('form' => zen_draw_form('products', FILENAME_ZEN4ALL_CATEGORIES_PRODUCT_LISTING, 'action=update_attributes_copy_to_category&cPath=' . $cPath . (isset($_GET['page']) ? '&page=' . $_GET['page'] : ''), 'post', 'class="form-horizontal"') . zen_draw_hidden_field('products_id', $pInfo->products_id) . zen_draw_hidden_field('categories_update_id', $_GET['categories_update_id']) . zen_draw_hidden_field('copy_attributes', $_GET['copy_attributes'])); $contents[] = array('text' => zen_draw_label(TEXT_COPY_ATTRIBUTES_CONDITIONS, 'copy_attributes', 'class="control-label"') . '
' . zen_draw_radio_field('copy_attributes', 'copy_attributes_delete', true) . TEXT_COPY_ATTRIBUTES_DELETE . '
' . zen_draw_radio_field('copy_attributes', 'copy_attributes_update') . TEXT_COPY_ATTRIBUTES_UPDATE . '
' . zen_draw_radio_field('copy_attributes', 'copy_attributes_ignore') . TEXT_COPY_ATTRIBUTES_IGNORE . '
'); $contents[] = array('text' => zen_draw_products_pull_down_categories('categories_update_id', 'class="form-control"', '', true)); $contents[] = array('align' => 'center', 'text' => ' '); break; // attribute copier to product case 'attribute_features_copy_to_product': $_GET['products_update_id'] = ''; // excluded current product from the pull down menu of products $products_exclude_array = []; $products_exclude_array[] = $pInfo->products_id; $heading[] = array('text' => '
' . TEXT_INFO_HEADING_ATTRIBUTE_FEATURES . $pInfo->products_id . '
'); $contents = array('form' => zen_draw_form('products', FILENAME_ZEN4ALL_CATEGORIES_PRODUCT_LISTING, 'action=update_attributes_copy_to_product&cPath=' . $cPath . (isset($_GET['page']) ? '&page=' . $_GET['page'] : ''), 'post', 'class="form-horizontal"') . zen_draw_hidden_field('products_id', $pInfo->products_id) . zen_draw_hidden_field('products_update_id', $_GET['products_update_id']) . zen_draw_hidden_field('copy_attributes', $_GET['copy_attributes'])); $contents[] = array('text' => zen_draw_label(TEXT_COPY_ATTRIBUTES_CONDITIONS, 'copy_attributes', 'class="control-label"') . '
' . zen_draw_radio_field('copy_attributes', 'copy_attributes_delete', true) . TEXT_COPY_ATTRIBUTES_DELETE . '
' . zen_draw_radio_field('copy_attributes', 'copy_attributes_update') . TEXT_COPY_ATTRIBUTES_UPDATE . '
' . zen_draw_radio_field('copy_attributes', 'copy_attributes_ignore') . TEXT_COPY_ATTRIBUTES_IGNORE . '
'); $contents[] = array('text' => zen_draw_products_pull_down('products_update_id', 'class="form-control"', $products_exclude_array, true)); $contents[] = array('align' => 'center', 'text' => ' '); break;

2.product page

1146 Table 'some.product_tabs_names' doesn't exist
in:
[SELECT pt.*, ptn.tab_name FROM product_tabs pt LEFT JOIN product_tabs_names ptn ON pt.id = ptn.id AND language_id = 1 ORDER BY pt.sort_order, ptn.tab_name]
If you were entering information, press the BACK button in your browser and re-check the information you had entered to be sure you left no blank fields.

**Comment by Zen4All** [comment]
1. Seems like I added two dummy files that were not ready for release
remove 
  - YOUR_ADMIN\includes\modals\categoriesProductListing\modalAttributeFeaturesCopyToProduct.php
  - YOUR_ADMIN\includes\modals\categoriesProductListing\modalAttributeFeaturesCopyToCategory.php
2. Looks like the file :YOUR_ADMIN\includes\installers\zen4all_cittins\2_0_0-beta_2.php never run
To create the missing tables you can use the creation code inside this file.

**Comment by ptzjl** [comment]
OK, but I wo n’t modify it. Will you fix it in the next version?

**Comment by Zen4All** [comment]
The files will be removed in a next release, until I have time to include the code. 
The SQL code should run on a fresh install. When the final version is released, all the sql will be in one file.

Thanks for your feedback.
